config/urls.py
# ----------------------------------------------------------------------------
# Copyright (c) 2016-2023, QIIME 2 development team.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------

from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('', include(('workshops.payments.urls', 'payments'))),
]

# Debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

payments/urls.py
from django.conf.urls import url

from . import views

app_name = 'payments'
urlpatterns = [
    url(r'^$', views.WorkshopList.as_view(),
        name='index'),
    url(r'^submit/$', views.SubmitOrder.as_view(),
        name='submit'),
    url(r'^postback/$', views.OrderPostback.as_view()),
    url(r'^(?P<slug>[\w\-]+)/$', views.WorkshopDetail.as_view(),
        name='details'),
    url(r'^(?P<slug>[\w\-]+)/order/$', views.OrderDetail.as_view(),
        name='order_details'),
    url(r'^(?P<slug>[\w\-]+)/confirm/$', views.ConfirmOrder.as_view(),
        name='confirm')
]

workshops/payments/urls.py
# ----------------------------------------------------------------------------
# Copyright (c) 2016-2023, QIIME 2 development team.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------
from django.urls import path, include

from .views import (
    WorkshopList, SubmitOrder, WorkshopDetail, OrderDetail, ConfirmOrder, OrderCallback)

app_name = 'payments'
urlpatterns = [
    path('', WorkshopList.as_view(), name='index'),
    path('confirm/', OrderCallback.as_view(), name='callback'),
    path('submit/', SubmitOrder.as_view(), name='submit'),
    path('<slug:slug>/', include([
        path('', WorkshopDetail.as_view(), name='details'),
        path('order/', OrderDetail.as_view(), name='order_details'),
        path('confirm/', ConfirmOrder.as_view(), name='confirm'),
    ]))
]

workshops/payments/models.py
# ----------------------------------------------------------------------------
# Copyright (c) 2016-2023, QIIME 2 development team.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------

import datetime
import uuid

from django.urls import reverse
from django.db import models
from django.db.models.expressions import F
from django.core.exceptions import ValidationError


from markdownx.models import MarkdownxField


class Workshop(models.Model):
    title = models.CharField(max_length=300)
    dedicated_qiime2 = models.BooleanField(default=False)
    location = models.CharField(max_length=300)
    description = MarkdownxField()
    email_description = MarkdownxField(help_text='This is the text that is '
                                       'emailed to all workshop attendees '
                                       'when their payment is processed. '
                                       'Supports Markdown.',
                                       blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    url = models.URLField(verbose_name='URL', max_length=2000, blank=True)
    slug = models.SlugField(help_text='This is the unique identifier for the '
                            'URL (i.e. title-YYYY-MM-DD)')
    draft = models.BooleanField(help_text='Draft workshops do not show up on '
                                'the workshop list overview', default=True)
    inline_purchase_instructions = MarkdownxField(help_text='This is the text '
                                                  'that is rendered on the '
                                                  'per-ticket sale page. Use '
                                                  'this field to provide '
                                                  'additional instructions. '
                                                  'Supports Markdown.',
                                                  blank=True)

    @property
    def total_tickets_sold(self):
        return OrderItem.objects.filter(rate__workshop=self) \
                .exclude(order__billed_total='') \
                .exclude(order__refunded=True).count()

    @property
    def is_open(self):
        return self.rate_set.filter(private=False, sold_out=False,
                                    sales_open=True).count() != 0

    @property
    def available_rates(self):
        return self.rate_set.filter(sold_out=False)

    @property
    def sold_out_rates(self):
        return self.rate_set.filter(sold_out=True)

    class Meta:
        unique_together = (('title', 'slug'),)

    def clean(self):
        # Make sure the workshop begins before it can end...
        if self.start_date > self.end_date:
            raise ValidationError('A Workshop\'s start date must be before '
                                  'the end date.')
        return super().clean()

    def __str__(self):
        return self.title

    # For django admin 'view on site' link
    def get_absolute_url(self):
        return reverse('payments:details', kwargs={'slug': self.slug})

    def filter_rates(self, rate_code):
        rate_set = None
        if rate_code:
            rate_set = self.rate_set.filter(
                discount_code=rate_code, sales_open=True).order_by('price')

        if rate_code is None or len(rate_set) == 0:
            rate_set = self.rate_set.filter(
                private=False, sales_open=True).order_by('price')
        return rate_set.all()


class Instructor(models.Model):
    name = models.CharField(max_length=300)
    # Allow blanks otherwise workshops are needed to be assigned upon creation
    workshops = models.ManyToManyField(Workshop, related_name='instructors',
                                       blank=True)

    def __str__(self):
        return self.name


class RateManager(models.Manager):
    def get_queryset(self):
        stale_age = datetime.datetime.utcnow() - datetime.timedelta(minutes=15)
        return super().get_queryset() \
            .annotate(ticket_count=models.Sum(
                models.Case(
                    models.When(
                        orderitem__order__refunded=True,
                        then=0
                    ),
                    models.When(
                        orderitem__order__order_datetime__gte=stale_age,
                        then=0
                    ),
                    models.When(
                        orderitem__order__order_datetime__lt=stale_age,
                        orderitem__order__billed_total='',
                        then=0
                    ),
                    models.When(
                        orderitem__order__order_datetime__lt=stale_age,
                        orderitem__order__billed_total__isnull=True,
                        then=0
                    ),
                    models.When(
                        orderitem__isnull=True,
                        then=0
                    ),
                    default=1,
                    output_field=models.IntegerField(),
                ))) \
            .annotate(sold_out=models.Case(
                          models.When(
                              ticket_count__lt=F('capacity'),
                              then=models.Value(False),
                          ),
                          default=True,
                          output_field=models.BooleanField(),
                        ))


class PosterOption(models.Model):
    workshop = models.ForeignKey(Workshop, on_delete=models.CASCADE)
    name = models.CharField(max_length=300)
    sort_order = models.IntegerField(help_text='This value is used to sort '
                                     'the display order of the poster '
                                     'presentation options')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('sort_order',)


class MeetingOption(models.Model):
    workshop = models.ForeignKey(Workshop, on_delete=models.CASCADE)
    name = models.CharField(max_length=300)
    sort_order = models.IntegerField(help_text='This value is used to sort '
                                     'the display order of the BYOD '
                                     'meeting options')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('sort_order',)


class Rate(models.Model):
    workshop = models.ForeignKey(Workshop, on_delete=models.CASCADE)
    name = models.CharField(max_length=300)
    price = models.DecimalField(max_digits=8, decimal_places=2,
                                verbose_name='price (USD)')
    max_order = models.PositiveIntegerField(null=True, default=None, blank=True)
    capacity = models.PositiveIntegerField()
    private = models.BooleanField(default=False)
    discount_code = models.SlugField(help_text='This will be the code given to'
                                     ' a customer receiving a discount in the '
                                     'form of https://workshops.qiime2.org/wor'
                                     'kshop_slug/rate=discount_code',
                                     blank=True)
    sales_open = models.BooleanField(default=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, default=None,
                               null=True, blank=True)

    objects = RateManager()

    def clean(self):
        # assign a UUID if it is a discount, but no custom code was given
        if self.private:
            if not self.discount_code:
                self.discount_code = uuid.uuid4()
            else:
                res = Rate.objects.filter(discount_code=self.discount_code)
                if len(res) > 0 and self not in res:
                    raise ValidationError(
                        'Discount codes must be unique. The code %s on the %s '
                        'is already in use.' % (self.discount_code, self)
                    )

        return super().clean()

    def __str__(self):
        return '%s ($%s)' % (self.name, self.price)


class Order(models.Model):
    transaction_id = models.UUIDField(default=uuid.uuid4, editable=False)
    contact_name = models.CharField(max_length=300)
    contact_email = models.EmailField()
    order_total = models.DecimalField(max_digits=7, decimal_places=2,
                                      verbose_name='order total (USD)')
    order_datetime = models.DateTimeField(auto_now_add=True)
    billed_total = models.CharField(
        blank=True,
        max_length=300,
        verbose_name='billed total (USD)',
        help_text='This is the confirmed paid amount from NAU'
    )
    billed_datetime = models.CharField(
        blank=True,
        max_length=300,
        help_text='This is the confirmed date and time of payment',
        verbose_name='billed date & time'
    )
    refunded = models.BooleanField(default=False)

    def __str__(self):
        return '%s: $%s on %s' % (self.contact_email, self.order_total,
                                  self.order_datetime)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    rate = models.ForeignKey(Rate, on_delete=models.CASCADE)
    poster = models.ForeignKey(PosterOption, null=True, on_delete=models.CASCADE)
    meeting = models.ForeignKey(MeetingOption, null=True, on_delete=models.CASCADE)
    email = models.EmailField()
    name = models.CharField(max_length=500)

    def __str__(self):
        return str(self.email)

    class Meta:
        unique_together = (('order', 'rate', 'email'), )

workshops/payments/forms.py
# ----------------------------------------------------------------------------
# Copyright (c) 2016-2023, QIIME 2 development team.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------


import functools

from django import forms

from .models import PosterOption, MeetingOption


class OrderForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': "Orderer's Name",
                                      'class': 'input'})
    )
    email = forms.EmailField(
        widget=forms.TextInput(attrs={'placeholder': "Orderer's Email Address",
                                      'class': 'input'})
    )

    def __init__(self, *args, **kwargs):
        workshop = kwargs.pop('workshop')
        discount_code = kwargs.pop('discount_code')
        super().__init__(*args, **kwargs)

        self.rate_set = workshop.filter_rates(discount_code)
        for rate in self.rate_set:
            self.fields[rate.name] = forms.IntegerField(
                initial=0,
                min_value=0,
                max_value=rate.max_order if rate.max_order else rate.capacity - rate.ticket_count,
                widget=forms.NumberInput(attrs={'class': 'input'})
            )
        for rate in workshop.sold_out_rates.all():
            self.fields[rate.name] = forms.IntegerField(
                initial=0,
                min_value=0,
                disabled=True,
                widget=forms.NumberInput(attrs={'class': 'input'})
            )

    def clean(self):
        cleaned_data = super().clean()
        rates = {}
        for rate in self.rate_set:
            try:
                rates[rate.name] = cleaned_data[rate.name]
            except KeyError:
                return cleaned_data

        if not functools.reduce(lambda x, y: x + y, rates.values()):
            raise forms.ValidationError('Order can not be empty.')

        return cleaned_data


class OrderDetailForm(forms.Form):
    def __init__(self, *args, **kwargs):
        workshop = kwargs.pop('workshop')
        super().__init__(*args, **kwargs)
        poster_qs = PosterOption.objects.filter(workshop__slug=workshop)
        if poster_qs.count() != 0:
            self.fields['poster_option'] = forms.ModelChoiceField(
                queryset=poster_qs)

        meeting_qs = MeetingOption.objects.filter(workshop__slug=workshop)
        if meeting_qs.count() != 0:
            self.fields['meeting_option'] = forms.ModelChoiceField(
                queryset=meeting_qs)

    email = forms.EmailField(
        widget=forms.TextInput(attrs={'placeholder': 'Ticketholder\'s Email',
                                      'class': 'input'})
    )
    name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Ticketholder\'s Name',
                                      'class': 'input'})
    )
    rate = forms.CharField(widget=forms.HiddenInput())


class OrderDetailFormSet(forms.BaseFormSet):
    def clean(self):
        if any(self.errors):
            return
        emails = []
        for form in self.forms:
            email = form.cleaned_data['email']
            if email in emails:
                raise forms.ValidationError('Tickets must have a unique '
                                            'email address.')
            emails.append(email)

workshops/payments/templates/payments/_draft_notice.html
{% if user.is_authenticated %}
    <div class="notification is-warning">
      You are currently logged in. The content available to you may
      differ from that of an anonymous user.
    </div>
  {# TODO: Fix capacity and public checks #}
  {% if workshop.draft or workshop.is_at_capacity %}
    <div class="notification is-danger">
      Current workshop is
      {% if not workshop.public %}
        a private workshop that is
      {% endif %}
      {% if workshop.draft %}
        marked as draft,
      {% elif workshop.is_at_capacity %}
        sold out,
      {% endif %}
      and is only viewable by site administrators.
    </div>
  {% endif %}
{% endif %}

workshops/payments/templates/payments/_form_errors.html
{% if form.errors.items or form.non_form_errors %}
  <div class="alert alert-danger">
    <ul>
      {% for name, errors in form.errors.items %}
        {% if name == '__all__' %}
          <li>{{ errors|join:', ' }}</li>
        {% else %}
          <li>{{ name | capfirst }}: {{ errors|join:', ' }}</li>
        {% endif %}
      {% endfor %}
      {% for error in form.non_form_errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  </div>
{% endif %}

workshops/payments/templates/payments/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}">
  <title>{% block 'title' %}QIIME 2 Workshops{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
  {% block 'head' %}{% endblock %}
  {% if not debug %}
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-86671044-5', 'auto');
      ga('send', 'pageview');
    </script>
  {% endif %}
</head>
<body>
  <nav class="navbar is-light" role="navigation" aria-label="main navigation">
    <div class="container">
      <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'payments:index' %}">
          <img class="header" src="{% static 'img/q2workshops.svg' %}" alt="QIIME 2" style="max-height: 40px;">
        </a>
        <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div class="navbar-menu" id="navMenu">
        <div class="navbar-start">
        </div>
        <div class="navbar-end">
          <a class="navbar-item {% if request.resolver_match.url_name == 'index' %}is-active{% endif %}" href="{% url 'payments:index' %}">
            Home
          </a>
          <div class="navbar-item has-dropdown is-hoverable">
            <p class="navbar-link">
              Resources
            </p>
            <div class="navbar-dropdown is-boxed">
              <a class="navbar-item" target="_blank" href="https://docs.qiime2.org/">
                Docs
              </a>
              <a class="navbar-item" target="_blank" href="https://dev.qiime2.org/">
                Dev Docs
              </a>
              <a class="navbar-item" target="_blank" href="https://forum.qiime2.org/">
                Forum
              </a>
              <a class="navbar-item" target="_blank" href="https://library.qiime2.org/">
                Library
              </a>
              <a class="navbar-item" target="_blank" href="https://qiime2.org/">
                Main Site
              </a>
              <a class="navbar-item" target="_blank" href="https://view.qiime2.org/">
                View
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <section class="section">
    <div class="container content">
      {% include 'payments/_draft_notice.html' %}
      {% block 'content' %}{% endblock %}
      <p>{{ TECHNICAL_CONTACT|safe }}</p>
    </div>
  </section>
  <footer class="footer" style="padding-bottom: 3rem;">
    <div class="content has-text-centered">
      <p>
      &#169; 2016-2021, <strong>QIIME 2 development team</strong>
      </p>
    </div>
  </footer>

  {% block 'footer' %}{% endblock %}
  <script>
    // https://bulma.io/documentation/components/navbar/#navbarJsExample
    document.addEventListener('DOMContentLoaded', function() {
      var burgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
      if (burgers.length > 0) {
        burgers.forEach(function(burger) {
          burger.addEventListener('click', function() {
            var target = burger.dataset.target;
            var targetEl = document.getElementById(target);
            burger.classList.toggle('is-active');
            targetEl.classList.toggle('is-active');
          });
        });
      }
    });
  </script>
</body>
</html>

workshops/payments/templates/payments/invoice.html
<!doctype base.html>
<html>
<head>
    <meta charset="utf-8">
    <title>Invoice</title>
    <style type="text/css">
        @page
        {
            size: A4;
            margin: 1cm;
        }
        .table
        {
            padding-top: 2px;
            padding-bottom: -2px;
            border-top: 1px solid #000;
            border-bottom: 1px solid #000;
            border-left: 1px solid #000;
            border-right: 1px solid #000;
            text-align: center;
            border-collapse: collapse;
        }
        .table th
        {
            background-color: #F2F2F2;
        }
        #top_left
        {
            padding-top: 4px;
            font-weight: bold;
        }
        #left
        {
            font-weight: bold;
        }
        #top_right
        {
            text-align: right;
            vertical-align: bottom;
            padding-top: 4px;
        }
        #right
        {
            text-align: right;
            vertical-align: bottom;
        }
        .list dt
        {
            font-weight: bold;
        }
        .list dd
        {
            padding-left: 15px
        }
    </style>
</head>
<body>
{% load static %}
<img src="workshops/static/img/q2logo.png" alt="Logo" height="77" width="170">
<p>
    {{ MAILING_ADDRESS|safe }}
    T: (928) 523-0688 | F: (928) 523-4015 | www.qiime2.org | pmi@nau.edu
</p>
<div>
    <table class="table">
        <thead>
        <tr>
            <th>WORKSHOP</th>
            <th>WORKSHOP DATE</th>
            <th>LOCATION</th>
            <th>INVOICE TERMS</th>
            <th>PAYMENT DUE</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ workshop.title }}</td>
                <td>{{ workshop.start_date }} - {{ workshop.end_date }}</td>
                <td>{{ workshop.location }}</td>
                <td>PREPAID-ONLINE PAYMENT</td>
                <td>PAID</td>
            </tr>
        </tbody>
    </table>
</div>
<div><br></div>
<div>
    <table class="table">
        <thead>
        <tr>
            <th>NAME</th>
            <th>EMAIL</th>
            <th>DESCRIPTION</th>
            <th>UNIT PRICE</th>
            <th>Administrative Processing Tax</th>
            <th>Amount</th>
        </tr>
        </thead>
        <tbody>
            {% for ticket in tickets %}
            <tr>
                <td>{{ ticket.name }}</td>
                <td>{{ ticket.email }}</td>
                <td>{{ ticket.rate.name }}</td>
                <td>${{ ticket.rate.price }}</td>
                <td>0.0%</td>
                <td>${{ ticket.rate.price }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div>
    <table>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td id="top_left">SUBTOTAL:</td>
            <td id="top_right">{{ total }}</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td id="left">ADMIN TAX RATE:</td>
            <td id="right">0.0%</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td id="left">ADMIN TAX:</td>
            <td id="right">$0.00</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td id="left">LESS PAID ONLINE:</td>
            <td id="right">$0.00</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td id="left">TOTAL DUE:</td>
            <td id="right">{{ total }}</td>
        </tr>
    </table>
</div>
<div>
    {{ BANK_INFO|safe }}
</div>
<div>
    <h2 style="color:#F00; padding-bottom:-15px">CHECK PAYMENTS</h2>
    <dl>
        <dt style="font-weight:bold">Checks should be made out to Northern Arizona University and mailed to the following address:</dt>
        <dd>
            {{ MAILING_ADDRESS|safe }}
        <dd>
    </dl>
</div>
</body>
</html>

workshops/payments/templates/payments/order_detail.html
{% extends 'payments/base.html' %}
{% load form_errors %}

{% block 'title' %}QIIME 2: {{ workshop.title }}{% endblock %}

{% block 'content' %}
<h1>{{ workshop.title }}</h1>
<p>Each ticket order must have contact info.</p>
<div id="instructions"></div>

{% form_errors formset %}
<form method="post" action="">
  {{ formset.management_form }}
  {% csrf_token %}
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Email</th>
      {%if zipped.0.form.poster_option%}<th>Poster Session</th>{%endif%}
      {%if zipped.0.form.meeting_option%}<th>Interactive Session</th>{%endif%}
      <th>Ticket Rate</th>
    </tr>
    {% for pair in zipped %}
      <tr>
        <td class="field">
          {% if pair.form.name.errors %}
            <label class="help is-danger">
              {{ pair.form.name.errors|join:", " }}
            </label>
          {% endif %}
          {{ pair.form.name }}
        </td>
        <td class="field">
          {% if pair.form.email.errors %}
            <label class="help is-danger">
              {{ pair.form.email.errors|join:", " }}
            </label>
          {% endif %}
          {{ pair.form.email }}
        </td>
        {% if pair.form.poster_option %}
        <td class="field">
          {% if pair.form.poster_option.errors %}
            <label class="has-text-danger">
              {{ pair.form.poster_option.errors|join:", " }}<br>
            </label>
          {% endif %}
          {{ pair.form.poster_option }}
        </td>
        {% endif %}
        {% if pair.form.meeting_option %}
        <td class="field">
          {% if pair.form.meeting_option.errors %}
            <label class="has-text-danger">
              {{ pair.form.meeting_option.errors|join:", " }}<br>
            </label>
          {% endif %}
          {{ pair.form.meeting_option }}
        </td>
        {% endif %}
        <td>{{ pair.rate }} {{ pair.form.rate }}</td>
      </tr>
    {% endfor %}
  </table>
  <input type="submit" class="button" value="Continue" />
</form>
{% endblock %}

{% block 'footer' %}
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script>
  var opts = {
    smartLists: true,
    sanitize: true,
  };
  document.getElementById('instructions').innerHTML = marked('{{ workshop.inline_purchase_instructions|escapejs }}', opts);
</script>
{% endblock %}

workshops/payments/templates/payments/workshop_confirm.html
{% extends 'payments/base.html' %}

{% block 'title' %}QIIME 2: {{ workshop.title }}{% endblock %}

{% block 'content' %}
  <h1>{{ workshop.title }}</h1>

  <p>
    The following is a summary of the order. Please use the 'back'
    functionality of your browser to fix any errors. If this looks okay, press
    'Submit Order' below to begin the payment process. Note: you will be taken
    to an off-site location to complete payment (payments are facilitated in
    part by Northern Arizona University, NAU). You will have the option to
    print or email your receipt at time of payment. Please do not proceed to
    next screen until you are ready to provide payment details.
  </p><br />

  <dl>
    <dt><strong>Title</strong></dt>
    <dd>{{ workshop.title }}</dd>

    <dt><strong>Dates</strong></dt>
    <dd>{{ workshop.start_date }} - {{ workshop.end_date }}</dd>

    <dt><strong>Order Contact Name</strong></dt>
    <dd>{{ order_name }}</dd>

    <dt><strong>Order Contact Email</strong></dt>
    <dd>{{ order_email }}</dd>

    <dt><strong>Order Total</strong></dt>
    <dd>{{ order_total }} USD</dd>
  </dl>

  <table class="table">
    <tr>
      <th>Ticketholder Name</th>
      <th>Ticketholder Email</th>
      {%if workshop.posteroption_set.count %}
        <th>Poster Session Interest</th>
      {%endif%}
      {%if workshop.meetingoption_set.count %}
        <th>Interactive Session Interest</th>
      {%endif%}
      <th>Ticket Rate</th>
    </tr>
    {% for ticket in tickets %}
      <tr>
        <td>{{ ticket.name }}</td>
        <td>{{ ticket.email }}</td>
        {%if workshop.posteroption_set.count %}
          <td>{{ ticket.poster }}</td>
        {%endif%}
        {%if workshop.meetingoption_set.count %}
          <td>{{ ticket.meeting }}</td>
        {%endif%}
        <td>{{ ticket.rate }}</td>
      </tr>
    {% endfor %}
  </table>
  <form method="post" action="{% url 'payments:submit' %}">
    {% csrf_token %}
    <input type="submit" class="button" value="Submit Order"/>
  </form>
{% endblock %}

workshops/payments/templates/payments/workshop_list.html
{% extends 'payments/base.html' %}

{% block 'title' %}QIIME 2: Workshops{% endblock %}
{% block 'content' %}

  {% if messages %}
    <div class="alert alert-warning">
      <ul>
      {% for message in messages %}
        <li>{{ message }}</li>
      {% endfor %}
      </ul>
    </div>
  {% endif %}

  <div>
    <p>{{ REQUEST_CONTACT|safe }}</p>
  </div>

  {% for category, workshops in workshop_categories.items %}
      <h3>{{ category | title }} Workshops</h3>
      {% if workshops %}
        <table class="table is-fullwidth is-hoverable">
          <thead>
            <tr>
              <th>Title</th>
              <th>Location</th>
              <th>Workshop Dates</th>
            </tr>
          </thead>
          <tbody>
            {% for workshop in workshops %}
              <tr>
                <td><a href="{% url 'payments:details' workshop.slug %}">{{ workshop.title }}</a></td>
                <td>{{ workshop.location }}</td>
                <td>{{ workshop.start_date }} - {{ workshop.end_date }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      {% else %}
        <p>No {{ category }} workshops</p>
      {% endif %}
  {% endfor %}
{% endblock %}